#web
quarkus.http.port=50900
quarkus.http.io-threads=20
#quarkus.vertx.worker-pool-size=

#monitoring
quarkus.smallrye-health.root-path=/actuator/health
quarkus.micrometer.export.prometheus.path=/actuator/prometheus
quarkus.swagger-ui.always-include=true

#jaeger
quarkus.jaeger.enabled=true
quarkus.jaeger.sampler-type=probabilistic
quarkus.jaeger.sampler-param=1
quarkus.jaeger.propagation=b3

quarkus.jaeger.service-name=callee-service
#quarkus.jaeger.endpoint=http://localhost:14268/api/traces

#security
security.authentication.enabled=true
%test.security.authentication.enabled=false

quarkus.oidc.application-type=hybrid
quarkus.oidc.roles.source=accesstoken

quarkus.oidc.client-id=callee-service
quarkus.oidc.auth-server-url=http://localhost:30100/oidc/auth/realms/tenant-0
#quarkus.http.proxy.enable-forwarded-prefix: "true"

#logging
quarkus.log.level=INFO

quarkus.log.category."org.goafabric".level=INFO
quarkus.log.category."org.flywaydb.core".level=INFO
quarkus.log.category."org.hibernate".level=INFO