FROM ghcr.io/graalvm/graalvm-ce:ol8-java17-22.2.0
RUN gu install native-image
WORKDIR /project
VOLUME ["/project"]
ENTRYPOINT ["native-image"]

#https://dev.to/nevernull/building-a-native-java-application-for-arm64-with-quarkus-2n9m
#docker build -f Dockerfile.build.aarch64 -t goafabric/quarkus-native-image:22.2-java17 .
#docker push goafabric/quarkus-native-image:22.2-java17

#docker run --rm -it ghcr.io/graalvm/graalvm-ce:ol8-java17-22.2.0 /bin/bash

