FROM ghcr.io/graalvm/graalvm-ce:java11-21.3.0@sha256:d3877ce3bae9538032f02d88fb5ea5019d5686a15dd15615fb4e9c65970c72cc AS build
RUN gu install native-image
WORKDIR /project
VOLUME ["/project"]
ENTRYPOINT ["native-image"]

#https://dev.to/nevernull/building-a-native-java-application-for-arm64-with-quarkus-2n9m
#docker build -f Dockerfile.build.aarch64 -t goafabric/quarkus-build-aarch64:java11-21.3.0 .
#docker push goafabric/quarkus-build-aarch64:java11-21.3.0

#docker run --rm -it ghcr.io/graalvm/graalvm-ce:java11-21.3.0@sha256:d3877ce3bae9538032f02d88fb5ea5019d5686a15dd15615fb4e9c65970c72cc /bin/bash

